name: 'airbnb'
version: '1.0.0'

profile: 'airbnb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  airbnb:
    listings:
      +column_types:
        id: BIGINT
        host_id: BIGINT
        minimum_nights: BIGINT
        price: VARCHAR
        created_at: TIMESTAMPTZ
        updated_at: TIMESTAMPTZ
    reviews:
      +column_types:
        listing_id: BIGINT
        date: TIMESTAMPTZ
      +quote_char: ""

models:
  airbnb:
    bronze:
      +materialized: table
    silver:
      +materialized: table
    gold:
      +materialized: view